function B(t,e){return Math.random()*(e-t)+t}function C(t,e,n,i){var s=t-n,o=e-i
return Math.sqrt(Math.pow(s,2)+Math.pow(o,2))}function D(t,e,n,i){for(this.x=t,this.y=e,this.sx=t,this.sy=e,this.tx=n,this.ty=i,this.distanceToTarget=C(t,e,n,i),this.distanceTraveled=0,this.coordinates=[],this.coordinateCount=3;this.coordinateCount--;)this.coordinates.push([this.x,this.y])
this.angle=Math.atan2(i-e,n-t),this.speed=2,this.acceleration=1.05,this.brightness=B(50,70),this.targetRadius=1}function E(t,e,n,i){for(this.x=t,this.y=e,this.sx=t,this.sy=e,this.tx=n,this.ty=i,this.distanceToTarget=C(t,e,n,i),this.distanceTraveled=0,this.coordinates=[],this.coordinateCount=3;this.coordinateCount--;)this.coordinates.push([this.x,this.y])
this.angle=Math.atan2(i-e,n-t),this.speed=1,this.acceleration=1.05,this.brightness=B(50,70),this.targetRadius=1}function F(t,e){for(this.x=t,this.y=e,this.coordinates=[],this.coordinateCount=5;this.coordinateCount--;)this.coordinates.push([this.x,this.y])
this.angle=B(0,2*Math.PI),this.speed=B(1,10),this.friction=.95,this.gravity=1,this.hue=B(hue-20,hue+20),this.brightness=B(50,80),this.alpha=1,this.decay=B(.015,.03)}function G(t,e,n,i,s,o,a){for(this.x=t,this.y=e,this.coordinates=[],this.coordinateCount=5;this.coordinateCount--;)this.coordinates.push([this.x,this.y])
this.angle=n,this.speed=i,this.friction=.95,this.gravity=1,this.hue=B(s-5,s+5),this.brightness=B(o,a),this.alpha=1,this.decay=B(.005,.01)}function H(t,e){for(var n=30;n--;)particles.push(new F(t,e))}function I(t,e){for(var n=[[0,10,60],[Math.PI/6,10,60],[Math.PI/3,10,60],[Math.PI/2,10,60],[2*Math.PI/3,10,60],[5*Math.PI/6,10,60],[Math.PI,10,60],[7*Math.PI/6,10,60],[4*Math.PI/3,10,60],[3*Math.PI/2,10,60],[5*Math.PI/3,10,60],[11*Math.PI/6,10,60]],i=[[.682317,6.18466,30],[1.5708,4.4,30],[2.45928,6.18466,30],[1.84537,7.37631,30],[1.29622,7.37631,30]],s=[[-.537108,5.17929,0],[-.851966,5.31507,0],[-1.11695,4.5618,0],[-1.20474,3.21286,0],[-.785398,2.12132,0],[0,2.4,0],[.397874,3.74233,0],[.114877,5.2345,0],[-.0660801,6.81487,0],[-.217293,7.88543,0],[-.378142,7.85493,0],[-.515549,6.89638,0],[-2.60448,5.17929,0],[-2.62604,6.89638,0],[-2.76345,7.85493,0],[-2.9243,7.88543,0],[-3.07551,6.81487,0],[3.02672,5.2345,0],[2.74372,3.74233,0],[3.14159,2.4,0],[-2.35619,2.12132,0],[-1.93685,3.21286,0],[-2.02464,4.5618,0],[-2.28963,5.31507,0]],o=0,a=0;a<n.length;a++)customParticles.push(new G(t,e,n[a][0]+o,n[a][1],n[a][2],50,80))
for(var a=0;a<i.length;a++)customParticles.push(new G(t,e,i[a][0]+o,i[a][1],i[a][2],20,40))
for(var a=0;a<s.length;a++)customParticles.push(new G(t,e,s[a][0]+o,s[a][1],s[a][2],50,80))}function J(){requestId=A(J),hue+=.5,ctx.globalCompositeOperation="destination-out",ctx.fillStyle="rgba(0, 0, 0, 0.5)",ctx.fillRect(0,0,cw,ch),ctx.globalCompositeOperation="lighter"
for(var t=fireworks.length;t--;)fireworks[t].draw(),fireworks[t].update(t)
for(var t=particles.length;t--;)particles[t].draw(),particles[t].update(t)
timerTick>=timerTotal?mousedown||(fireworks.push(new D(cw/2,ch,B(0,cw),B(0,ch/2))),timerTick=0):timerTick++}function K(){requestId1=A(K),hue+=2,ctx.globalCompositeOperation="destination-out",ctx.fillStyle="rgba(0, 0, 0, 0.5)",ctx.fillRect(0,0,cw,ch),ctx.globalCompositeOperation="lighter"
for(var t=fireworks.length;t--;)fireworks[t].draw(),fireworks[t].update(t)
for(var t=particles.length;t--;)particles[t].draw(),particles[t].update(t)
fireworks.push(new D(cw/2,ch,B(0,cw),B(0,ch/2)))}function L(){requestId2=A(L),ctx.globalCompositeOperation="destination-out",ctx.fillStyle="rgba(0, 0, 0, 0.5)",ctx.fillRect(0,0,cw,ch),ctx.globalCompositeOperation="lighter"
for(var t=customFireworks.length;t--;)customFireworks[t].draw(),customFireworks[t].update(t)
for(var t=customParticles.length;t--;)customParticles[t].draw(),customParticles[t].update(t)
customTimerTick>=customTimerTotal?mousedown||(customFireworks.push(new E(cw/2,ch,B(0,cw),B(0,ch/2))),customTimerTick=0):customTimerTick++}function M(){requestId2=A(M),ctx.globalCompositeOperation="destination-out",ctx.fillStyle="rgba(0, 0, 0, 0.5)",ctx.fillRect(0,0,cw,ch),ctx.globalCompositeOperation="lighter"
for(var t=customFireworks.length;t--;)customFireworks[t].draw(),customFireworks[t].update(t)
for(var t=customParticles.length;t--;)customParticles[t].draw(),customParticles[t].update(t)
customTimer2Tick>=customTimer2Total?mousedown||(customFireworks.push(new E(cw/2,ch,B(0,cw),B(0,ch/2))),customTimer2Tick=0):customTimer2Tick++}function N(t,e){t.style.opacity=0,t.style.display="block"
var n=+new Date,i=function(){t.style.opacity=+t.style.opacity+(new Date-n)/e,n=+new Date,+t.style.opacity<1&&(window.requestAnimationFrame&&requestAnimationFrame(i)||setTimeout(i,16))}
i()}function O(t,e){t.style.opacity=1
var n=+new Date,i=function(){t.style.opacity=+t.style.opacity-(new Date-n)/e,n=+new Date,t.style.opacity>0&&(window.requestAnimationFrame&&requestAnimationFrame(i)||setTimeout(i,16))}
i()}function P(t,e,n,i,s,o,a,r,u){messageDisplay&&subCount<t-100&&(clearTimeout(showID),clearTimeout(happyID),messageDisplay=!1,setTimeout(function(){setTimeout(function(){_("imageLink").style.display="none",_("channelThumbnail").style.display="none",_("subscribeButton").style.display="none"},1e3),_("happyMarquee").style.width="90%",_("happyMarquee").style.fontSize="2.5vw",_("happyMarquee").style.color="#f00",_("happyMarquee").innerHTML='You may submit a message for the Ballingers <a id="messageLink" target="_blank" href="http://www.livecounts.x10host.com/ballingersform.php">here</a>. Your message will be displayed on Livecounts when they hit 600k.',N(happyMarquee,1e3),setTimeout(function(){O(happyMarquee,2e3),setTimeout(function(){_("happyMarquee").style.display="none",_("imageLink").style.display="",_("channelThumbnail").style.display="",JJ(imageLink,1e3),JJ(channelThumbnail,1e3),N(subscribeButton,1e3)},2e3)},1e4)},2e3)),subCount>=t+n?passed3M1c||void 0!==requestId&&V():subCount>=t&&!passed3M?U(i,"https://livecounts.net/messages"+s+".txt"):(_("updateText").style.fontSize="3vw",1==u?(d=new Date,hour=d.getUTCHours()-6+d.getUTCMinutes()/60,lower=T(parseInt(subCount,10),hour,o/24*r,t)-1,upper=T(parseInt(subCount,10),hour,o/24*a,t),_("updateText").innerHTML="Estimated time to reach "+e+": <b>"+(lower<=0?"< ":lower+"&ndash;")+upper+(1==upper?" hour":" hours")+"</b>"):(hour=(t-subCount)/o,lower=Math.floor(hour*a),upper=Math.ceil(hour*r),_("updateText").innerHTML="Estimated time to reach "+e+": <b>"+(lower<=0?"< ":lower+"&ndash;")+upper+(1==upper?" day":" days")+"</b>"))}function Q(t){var e=t.toString(16)
return 1==e.length?"0"+e:e}function R(t,e,n){return"#"+Q(t)+Q(e)+Q(n)}function S(t,e){var n=t*Math.PI/12
return(31*Math.sin(n+3.1)-8.2*Math.sin(2*n-.5))*((e+23)/80)+e}function T(t,e,n,i){for(var s=0;i>t;)t+=S(++e,n),s++
return s}function U(t,e){showBtn=!1,K(),setTimeout(function(){window.cancelAnimationFrame(requestId1)},5e3),J(),"Miranda"==t&&setTimeout(function(){L()},7e3),"Ballinger family"==t&&(_("congratsText").style.fontSize="5vw"),document.body.style.backgroundColor="#68727F",O(_("title"),2e3),O(_("byline"),2e3),O(_("imageLink"),2e3),O(_("channelThumbnail"),2e3),O(_("subscribeButton"),2e3),O(_("smallText"),2e3),O(_("channelSubs2"),2e3),O(_("updateText"),2e3),_("congratsText").innerHTML="<b>Congratulations, "+t+"!</b>",N(_("congratsText"),2e3),_("nameLink").style.color=_("channelSubs").style.color="white",_("container").style.width="97%",passed3M=!0,setTimeout(function(){Y(e)},3e3)}function V(){var t=_("canvas"),e=t.getContext("2d")
window.cancelAnimationFrame(requestId),window.cancelAnimationFrame(requestId2),e.clearRect(0,0,t.width,t.height),OO(),_("updateText").style.fontSize="3vw",_("updateText").innerHTML="<i>updated every "+upInt+" seconds</i>",_("imageLink").style.display="",_("channelThumbnail").style.display="",JJ(imageLink,2e3),JJ(channelThumbnail,2e3),N(_("title"),2e3),N(_("byline"),2e3),N(_("subscribeButton"),2e3),N(_("smallText"),2e3),N(_("channelSubs2"),2e3),N(_("updateText"),2e3),O(_("congratsText"),2e3),O(_("messageText"),2e3),clearInterval(changeId),_("nameLink").style.color=_("channelSubs").style.color="black",_("container").style.width="40%",passed3M=!0,passed3M1c=!0}function X(t){for(var e,n,i,s=t.length/2;s;)i=Math.floor(Math.random()*s--),e=t[2*s],n=t[2*s+1],t[2*s]=t[2*i],t[2*s+1]=t[2*i+1],t[2*i]=e,t[2*i+1]=n
return t}function Y(t){var e,n,i,s,o=[],a=new XMLHttpRequest
a.open("GET",t,!0),a.onload=function(){function t(){e=o[u%o.length],s=window.innerWidth/window.innerHeight,n=e.length+200*s-550,i=n>0?3-n/150:3,s>1.6?_("messageText").style.top=70*(s-1.6)-28+"px":_("messageText").style.top="-28px",_("messageText").style.fontSize=i+"vw",_("messageText").innerHTML=e+"<br>"+o[(u+1)%o.length],N(_("messageText"),500),u+=2}if(a.status>=200&&a.status<400){s=window.innerWidth/window.innerHeight,s>1.6&&(_("messageText").style.top=70*(s-1.6)-28+"px")
var r=a.responseText
o=r.split("\n"),o=X(o),_("messageText").innerHTML="<b>A few words from us...</b>",N(_("messageText"),500)
var u=0
changeId=setInterval(function(){O(_("messageText"),500),setTimeout(t,500)},7e3)}},a.send()}function Z(t){var e=t.length<24?"forUsername":"id"
url1="https://www.googleapis.com/youtube/v3/channels?part=statistics&"+e+"="+t+"&fields=items/statistics/subscriberCount&key="+keys[whichone]
var n=new XMLHttpRequest
n.open("GET",url1,!0),n.onload=function(){if(n.status>=400)if(27==GG()){var e=Math.floor(3*Math.random())
alert("API quota exceeded. You will be redirected to another sub counter."),window.location=altCounters[e]+channel+altExt[e]}else{keysUsed>16&&(_("updateText").innerHTML="<i>updated every "+upInt+" seconds</i>",clearInterval(upId1),upId1=setInterval(function(){Z(t)},1e3*upInt)),++whichone,whichone%=27
var i=t.length<24?"forUsername":"id"
n.open("GET","https://www.googleapis.com/youtube/v3/channels?part=statistics&"+i+"="+t+"&fields=items/statistics/subscriberCount&key="+keys[whichone],!0),n.send()}if(n.status>=200&&n.status<400){var i=JSON.parse(n.responseText)
if(subCount=i.items[0].statistics.subscriberCount,subCount=parseInt(subCount,10),soundEnabled&&(subCount>oldCount?upAudio.play():subCount<oldCount&&downAudio.play()),oldCount=subCount,_("channelSubs").innerHTML=subCount,"UCsi7f6y5dH5uuye3MeCfojA"==t&&P(6e5,"600k",1e3,"Ballinger family",80,520,2/3,4/3,0),"UCo0w4w1XJZBXDT6l4EXZJAw"==t){var s=nightEnabled?0:128,o=Math.floor(128*Math.random()+s),a=Math.floor(128*Math.random()+s),e=Math.floor(128*Math.random()+s)
document.body.style.backgroundColor=R(o,a,e),_("updateText").style.fontSize="3vw",_("updateText").innerHTML="Estimated time to reach 1M: <b>Never</b>"}}},n.send()}function AA(t){var e=t.length<24?"user":"channel"
url2="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20html%20where%20url%20%3D%20%22https%3A%2F%2Fwww.youtube.com%2F"+e+"%2F"+t+"%2Fabout%22%20and%20xpath%3D%22%2F%2Fspan%5B%40aria-label%20and%20%40title%5D%2Ftext()%22&format=json"
var n=new XMLHttpRequest
n.open("GET",url2,!0),n.onload=function(){if(n.status>=200&&n.status<400){var t=JSON.parse(n.responseText)
subCount2=t.query.results,null!=subCount2?(subCount2=subCount2.replace(/\,/g,""),subCount2=parseInt(subCount2,10)):subCount2=0,_("channelSubs2").innerHTML=subCount2}},n.send()}function W(){var t=window.prompt("Enter channel name, username, ID, or URL:","")
null!=t&&""!=t&&(home=!1,entry=!1,EE(t),window.history.pushState("","","/channel/"+t))}function BB(){var t=window.prompt("Channel not found. Try entering the channel's URL.","")
null!=t&&""!=t?(EE(t),window.history.pushState("","","/channel/"+t)):(home=!0,II(),window.history.pushState("","","/"))}function CC(t,e,n){OO(),SS(e,"pageview",entry),window.clearInterval(upId1),window.clearInterval(upId2),_("updateText").innerHTML="<i>updated every "+upInt+" seconds</i>",home?ga("send","pageview",{page:"/",title:"Live Subscriber Count - Livecounts"}):(document.title=n+" ("+e+") Live Subscriber Count - Livecounts",ga("send","pageview",{page:"/channel/"+t,title:n+" ("+e+") Live Subscriber Count - Livecounts"})),chnamestr=e.length<24?"user":"channel",channelURL="https://www.youtube.com/"+chnamestr+"/"+e,_("channelLink").href=channelURL,_("imageLink").href=channelURL,_("subscribeForm").action=channelURL,_("subscribeButton").onclick=function(){HH(n,e)},Z(e),smallCountFunction(e),upId1=setInterval(function(){Z(e)},2e3),upId2=setInterval(function(){smallCountFunction(e)},3e4)}function DD(t,e){channeltext=channel=/"?([^"]*)"?/.exec(e)[1],chnamestr=channel.length<24?"forUsername":"id"
var n=new XMLHttpRequest
n.open("GET","https://www.googleapis.com/youtube/v3/channels?part=snippet&"+chnamestr+"="+channel+"&fields=items/snippet&key=AIzaSyBfaDKs6ky44Jza3InfqYiDiFnhaQrFCl0",!0),n.onload=function(){if(n.status>=200&&n.status<400){var e=JSON.parse(n.responseText)
null==e.items[0]?BB():(title=e.items[0].snippet.title,""!=title?_("nameLink").innerHTML="id"==chnamestr?title:channeltext:channel="",imgURL=e.items[0].snippet.thumbnails["default"].url,_("channelThumbnail").src=imgURL,_("channelThumbnail").alt=title,KK(title),CC(t,channel,title))}},n.send()}function EE(t){var e=t.trim()
"rezah"==e.toLowerCase()?e="rezahgaming":"ladyjay31"==e.toLowerCase()?e="UC2UYOjrz7NWZxw8s7a9hOig":("kinghusker"==e.toLowerCase()||"king husker"==e.toLowerCase()||"the king husker"==e.toLowerCase())&&(e="thekinghusker"),home?(hasDescription&&(_("container").style.display="none",_("description").style.display="block"),setTimeout(function(){home&&(N(container,2e3),O(description,2e3),setTimeout(function(){_("description").style.display="none"},2e3))},2e4)):(_("description").style.display="none",_("container").style.display="block"),position=e.indexOf("youtube.com/"),-1!==position?(c=e.substring(position+12),c1=c.split(/\/|\?/),c1=c1[1],"user/"==c.substring(0,5)||"channel/"==c.substring(0,8)?channel='"'+c1+'"':"c/"==c.substring(0,2)?channel="'"+c1+"'":channel=c):channel=e
var n=new XMLHttpRequest
"'"==channel.charAt(0)&&"'"==channel.charAt(channel.length-1)?(channeltext=channel=channel.slice(1,-1),n.open("GET","http://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20html%20where%20url%20%3D%20%22https://www.youtube.com/c/"+channel+"%22%20and%20xpath%3D%22%2F%2Fmeta%5B%40itemprop%3D'channelId'%5D%22&format=json",!0),n.onload=function(){if(n.status>=200&&n.status<400){var t=JSON.parse(n.responseText)
null!=t.query.results?(channel='"'+t.query.results.meta[0].content+'"',DD(e,channel)):BB()}},n.send()):channel.match(/^UC[A-Za-z0-9\-\_]{22}$/)||'"'==channel.charAt(0)&&'"'==channel.charAt(channel.length-1)?DD(e,channel):(n.open("GET","https://www.googleapis.com/youtube/v3/search?part=snippet&q="+channel+"&type=channel&fields=items/snippet&key="+channelKeys[whichone2],!0),n.onload=function(){if(n.status>=400)if(5==++channelKeysUsed){var t=Math.floor(3*Math.random())
alert("API quota exceeded. You will be redirected to another sub counter."),window.location=altCounters[t]+channel+altExt[t]}else++whichone2,whichone2%=5,n.open("GET","https://www.googleapis.com/youtube/v3/search?part=snippet&q="+channel+"&type=channel&fields=items/snippet&key="+channelKeys[whichone2],!0),n.send()
if(n.status>=200&&n.status<400){var t=JSON.parse(n.responseText)
null==t.items[0]?BB():(channel=t.items[0].snippet.channelId,title=t.items[0].snippet.title,_("nameLink").innerHTML=title,imgURL=t.items[0].snippet.thumbnails["default"].url,_("channelThumbnail").src=imgURL,_("channelThumbnail").alt=title,KK(title),CC(e,channel,title))}},n.send())}function FF(){var t=decodeURIComponent((RegExp("[?|&]channel=([^&;]+?)(&|#|;|$)").exec(location.search)||[,""])[1].replace(/\+/g,"%20"))||null
null==t?t=(/\/channel\/(.*)/.exec(window.location)||[,""])[1]:window.history.replaceState("","","/channel/"+t),""==t?(home=!0,II(),window.history.replaceState("","","/")):(home=!1,EE(t))}function GG(){return keysUsed++,keysUsed>16&&(upInt=5),keysUsed>23&&(upInt=10),keysUsed}function HH(t,e){ga("send",{hitType:"event",eventCategory:"Buttons",eventAction:"Subscribe",eventLabel:t+" ("+e+") ",nonInteraction:!0}),SS(e,"click",entry)}function II(){var t=new Date,e="https://livecounts.net/featured/"+(t.getUTCMonth()+1)+"-"+t.getUTCDate()+"-"+t.getUTCFullYear()%100+".txt",n=new XMLHttpRequest
n.open("GET",e,!0),n.onload=function(){if(n.status>=200&&n.status<400){var t=n.responseText,e=t.indexOf("\n"),i=t.slice(0,e),s=t.slice(e+1)
""==s&&(hasDescription=!1),_("description").innerHTML=s,EE(i)}else EE("PsychoSoprano")},n.send()}function JJ(t,e){t.style.opacity=0
var n=+new Date,i=function(){t.style.opacity=+t.style.opacity+(new Date-n)/e,n=+new Date,+t.style.opacity<1&&(window.requestAnimationFrame&&requestAnimationFrame(i)||setTimeout(i,16))}
i()}function KK(t){if("undefined"!=typeof shareButton){_("shareButton").innerHTML=""
var e=document.createElement("a")
e.setAttribute("href","https://twitter.com/share"),e.setAttribute("class","twitter-share-button"),e.setAttribute("data-text","View "+t+"'s live subscriber count on Livecounts!"),this.shareButton.appendChild(e),"undefined"==typeof twttr?!function(t,e,n){var i,s=t.getElementsByTagName(e)[0],o=/^http:/.test(t.location)?"http":"https"
t.getElementById(n)||(i=t.createElement(e),i.id=n,i.src=o+"://platform.twitter.com/widgets.js",s.parentNode.insertBefore(i,s))}(document,"script","twitter-wjs"):twttr.widgets.load()}}function LL(t){switch(t.charCode){case 110:nightEnabled=!nightEnabled,OO(),MM(nightEnabled?"Night mode ON":"Night mode OFF")
break
case 115:(void 0===upAudio||void 0===downAudio)&&(upAudio=new Audio("pingUp.mp3"),downAudio=new Audio("pingDown.mp3")),soundEnabled=!soundEnabled,MM(soundEnabled?"Sound ON":"Sound OFF")
break
case 99:RR(QQ),_("smallText").innerHTML="comments for the channel",MM("Comment count selected")
break
case 118:RR(PP),_("smallText").innerHTML="total video views",MM("View count selected")
break
case 121:RR(AA),_("smallText").innerHTML="count displayed on YouTube",MM("Subscriber count on YouTube selected")}}function MM(t){_("message").innerHTML=t,_("messageBox").style.display="table",clearTimeout(messageID),messageID=setTimeout(function(){_("messageBox").style.display="none"},1500)}function NN(t,e){_(t).style.color=e}function OO(){nightEnabled?(document.body.style.backgroundColor="#34393f",NN("title","#fff"),NN("byline","#fff"),NN("happyMarquee","#fff"),NN("nameLink","#fff"),NN("channelSubs","#fff"),NN("channelSubs2","#fff"),NN("smallText","#fff"),NN("nameLink","#fff"),NN("description","#08f"),NN("updateText","#fff")):(document.body.style.backgroundColor="#d0e4fe",NN("title","#000"),NN("byline","#000"),NN("happyMarquee","#000"),NN("nameLink","#000"),NN("channelSubs","#000"),NN("channelSubs2","#000"),NN("smallText","#000"),NN("nameLink","#000"),NN("description","#00f"),NN("updateText","#000"))}function PP(t){var e=t.length<24?"forUsername":"id"
url2="https://www.googleapis.com/youtube/v3/channels?part=statistics&"+e+"="+t+"&fields=items/statistics/viewCount&key="+keys[whichone]
var n=new XMLHttpRequest
n.open("GET",url2,!0),n.onload=function(){if(n.status>=400)if(27==GG()){var e=Math.floor(3*Math.random())
alert("API quota exceeded. You will be redirected to another sub counter."),window.location=altCounters[e]+channel+altExt[e]}else{++whichone,whichone%=27
var i=t.length<24?"forUsername":"id"
n.open("GET","https://www.googleapis.com/youtube/v3/channels?part=statistics&"+i+"="+t+"&fields=items/statistics/viewCount&key="+keys[whichone],!0),n.send()}if(n.status>=200&&n.status<400){var i=JSON.parse(n.responseText)
viewCount=i.items[0].statistics.viewCount,_("channelSubs2").innerHTML=viewCount}},n.send()}function QQ(t){var e=t.length<24?"forUsername":"id"
url2="https://www.googleapis.com/youtube/v3/channels?part=statistics&"+e+"="+t+"&fields=items/statistics/commentCount&key="+keys[whichone]
var n=new XMLHttpRequest
n.open("GET",url2,!0),n.onload=function(){if(n.status>=400)if(27==GG()){var e=Math.floor(3*Math.random())
alert("API quota exceeded. You will be redirected to another sub counter."),window.location=altCounters[e]+channel+altExt[e]}else{++whichone,whichone%=27
var i=t.length<24?"forUsername":"id"
n.open("GET","https://www.googleapis.com/youtube/v3/channels?part=statistics&"+i+"="+t+"&fields=items/statistics/commentCount&key="+keys[whichone],!0),n.send()}if(n.status>=200&&n.status<400){var i=JSON.parse(n.responseText)
commentCount=i.items[0].statistics.commentCount,_("channelSubs2").innerHTML=commentCount}},n.send()}function RR(t){smallCountFunction=t,window.clearInterval(upId2),t(channel),upId2=setInterval(function(){t(channel)},3e4)}function SS(t,e,n){var i=document.location,s=document.referrer,o=n?1:0,a=+new Date,r=document.createElement("img")
r.src="https://analytics.livecounts.net/count?t="+e+"&c="+t+"&l="+i+"&r="+s+"&e="+o+"&z="+a}function _(t){var e=document.getElementById(t)
return null===e?document.getElementById("nothing"):e}var messageDisplay=!0,passed3M=!1,passed3M1c=!1
window.A=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||function(t){window.setTimeout(t,1e3/60)}}()
var canvas=document.getElementById("canvas"),ctx=canvas.getContext("2d"),cw=window.innerWidth,ch=window.innerHeight,fireworks=[],customFireworks=[],particles=[],customParticles=[],hue=360*Math.random(),customHue=60,limiterTotal=5,limiterTick=0,timerTotal=160,customTimerTotal=220,customTimer2Total=220,timerTick=0,customTimerTick=0,customTimer2Tick=0,mousedown=!1,mx,my
canvas.width=cw,canvas.height=ch
var requestId,requestId1,requestId2
D.prototype.update=function(t){this.coordinates.pop(),this.coordinates.unshift([this.x,this.y]),this.targetRadius<8?this.targetRadius+=.3:this.targetRadius=1,this.speed*=this.acceleration
var e=Math.cos(this.angle)*this.speed,n=Math.sin(this.angle)*this.speed
this.distanceTraveled=C(this.sx,this.sy,this.x+e,this.y+n),this.distanceTraveled>=this.distanceToTarget?(H(this.tx,this.ty),fireworks.splice(t,1)):(this.x+=e,this.y+=n)},E.prototype.update=function(t){this.coordinates.pop(),this.coordinates.unshift([this.x,this.y]),this.targetRadius<8?this.targetRadius+=.3:this.targetRadius=1,this.speed*=this.acceleration
var e=Math.cos(this.angle)*this.speed,n=Math.sin(this.angle)*this.speed
this.distanceTraveled=C(this.sx,this.sy,this.x+e,this.y+n),this.distanceTraveled>=this.distanceToTarget?(I(this.tx,this.ty),customFireworks.splice(t,1)):(this.x+=e,this.y+=n)},D.prototype.draw=function(){ctx.beginPath(),ctx.moveTo(this.coordinates[this.coordinates.length-1][0],this.coordinates[this.coordinates.length-1][1]),ctx.lineTo(this.x,this.y),ctx.strokeStyle="hsl("+hue+", 100%, "+this.brightness+"%)",ctx.stroke(),ctx.beginPath()},E.prototype.draw=function(){ctx.beginPath(),ctx.moveTo(this.coordinates[this.coordinates.length-1][0],this.coordinates[this.coordinates.length-1][1]),ctx.lineTo(this.x,this.y),ctx.strokeStyle="hsl("+customHue+", 100%, "+this.brightness+"%)",ctx.stroke(),ctx.beginPath()},F.prototype.update=function(t){this.coordinates.pop(),this.coordinates.unshift([this.x,this.y]),this.speed*=this.friction,this.x+=Math.cos(this.angle)*this.speed,this.y+=Math.sin(this.angle)*this.speed+this.gravity,this.alpha-=this.decay,this.alpha<=this.decay&&particles.splice(t,1)},G.prototype.update=function(t){this.coordinates.pop(),this.coordinates.unshift([this.x,this.y]),this.speed*=this.friction,this.x+=Math.cos(this.angle)*this.speed,this.y+=Math.sin(this.angle)*this.speed+this.gravity,this.alpha-=this.decay,this.alpha<=this.decay&&customParticles.splice(t,1)},F.prototype.draw=function(){ctx.beginPath(),ctx.moveTo(this.coordinates[this.coordinates.length-1][0],this.coordinates[this.coordinates.length-1][1]),ctx.lineTo(this.x,this.y),ctx.strokeStyle="hsla("+this.hue+", 100%, "+this.brightness+"%, "+this.alpha+")",ctx.stroke()},G.prototype.draw=function(){ctx.beginPath(),ctx.moveTo(this.coordinates[this.coordinates.length-1][0],this.coordinates[this.coordinates.length-1][1]),ctx.lineTo(this.x,this.y),ctx.strokeStyle="hsla("+this.hue+", 100%, "+this.brightness+"%, "+this.alpha+")",ctx.stroke()}
var whichone=Math.floor((new Date).getTime()/32e5)%27,whichone2=Math.floor((new Date).getTime()/1728e4)%5,changeId,home,upId1,upId2,keys=["AIzaSyCRtJ2uhgYe7p3J-QkC6kHsm7KZz0bDIok","AIzaSyCo-PwQAtlrchgSAY0hLnE2HYSRhqdsPXk","AIzaSyC7asPTom1oZVPmZu7UcttGNFvqzRWQiRM","AIzaSyDmUVXdKMQfp1428NsX0GuBHEp3Hh6VnRQ","AIzaSyB0uq8HHarCnpYG4pZxYPwE8wLAtM_gBN0","AIzaSyCgp_Uc2jj1mAd7HW9AzAATt33rGkvttVQ","AIzaSyDUUfmvtaHY3lQ11CbkF8gplSJSXwgLe2g","AIzaSyDzUqDdCGrb5g5YU0fo0pB9QbqurkK3GSc","AIzaSyBgcyeGD9VK-Nu2pnlP5VQaLWqYSIPWZRk","AIzaSyAGry7aVXPytGcqt-GrOb4HkIXVGbuL4As","AIzaSyAiWjUpPAvVy1fLj2VTJitH56Gs-2PBMLY","AIzaSyA2bieaAnufzw9YNibt0R2WI14L8uU9tbw","AIzaSyDpTfaINBOTi_1YgYSmk25DPS8ex-duZsQ","AIzaSyAGFMcByfMdsbQbpK7FE8MfHLZNjMDIWsw","AIzaSyCLuua085lVPXp0Jmqb_AIePC0hG66N_5U","AIzaSyDGu5pdf-_0cNIZdNkcLKtdpn0UNulX7hU","AIzaSyDY8suw3_q3zMX6ZDhdr7IDpPLQ6CbEsoY","AIzaSyCE9cyVSRDrn0nCjO_ajRDSHXUr3yqLnT0","AIzaSyACVbv1wiiFdYQsaMQkthBJAUi-Ek-ZNkc","AIzaSyANLBp5fHf-XEsQnksu_-ygJMHviGQO7TY","AIzaSyCQXeXdjhu5SKnvLJeYz9SgyKbzT8fnQko","AIzaSyBlSrOJ-ajuFM4cRpbPbuBnI1Fn3BPFrbg","AIzaSyC9jt3y7ygY5qTToSUEanHCyMYonkCXz1w","AIzaSyA5dmZA8HwtRCI24FDlf4E0atZ5KjYxzWA","AIzaSyBBjLqNnzhnJ5xqRGwfdCmIVG13YNNNk2w","AIzaSyACZdXbrIijp3kLgAGNIdSCe7uxxIvo9wY","AIzaSyBKDw28djiaVr2rFLUUHEO2gNoa4SBa5Eo"],channelKeys=["AIzaSyAkedClIJENM-lKk5Hwziprb_E9G5bKopc","AIzaSyDdck0LEAXOCBVKDpN4ZgxC0Gk6zBedOTM","AIzaSyBiwDi5co4t3Fopz9oEcfoisthYZz_kivM","AIzaSyAm3hJqTq1L1wcz-cz_4zLUNs2PD37hLuY","AIzaSyC_oqi_gbXaI29dkJJMRs0a82OWcl-h3tU"],altCounters=["https://akshatmittal.com/youtube-realtime/#!/","http://socialblade.com/youtube/user/","http://subscribercounter.com/#!/"],altExt=["","/realtime",""],keysUsed=0,channelKeysUsed=0,upInt=2,showBtn=!0,upAudio,downAudio,oldCount=0,messageID,hasDescription=!0,showID,happyID,smallCountFunction=AA,entry=!0
if(function(){var t,e,n,i,s,o,a,r,u,h,l,c,d,p,m,f,y,w,g,b,v,T,M,x,k,C,I,A,S,L,_,E,N=[].slice
y='<span class="odometer-value"></span>',p='<span class="odometer-ribbon"><span class="odometer-ribbon-inner">'+y+"</span></span>",i='<span class="odometer-digit"><span class="odometer-digit-spacer">8</span><span class="odometer-digit-inner">'+p+"</span></span>",a='<span class="odometer-formatting-mark"></span>',n="(,ddd).dd",r=/^\(?([^)]*)\)?(?:(.)(d+))?$/,u=30,o=2e3,t=20,h=2,s=.5,l=1e3/u,e=1e3/t,m="transitionend webkitTransitionEnd oTransitionEnd otransitionend MSTransitionEnd",k=document.createElement("div").style,f=null!=k.transition||null!=k.webkitTransition||null!=k.mozTransition||null!=k.oTransition,M=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame,c=window.MutationObserver||window.WebKitMutationObserver||window.MozMutationObserver,g=function(t){var e
return e=document.createElement("div"),e.innerHTML=t,e.children[0]},T=function(t,e){return t.className=t.className.replace(RegExp("(^| )"+e.split(" ").join("|")+"( |$)","gi")," ")},w=function(t,e){return T(t,e),t.className+=" "+e},C=function(t,e){var n
return null!=document.createEvent?(n=document.createEvent("HTMLEvents"),n.initEvent(e,!0,!0),t.dispatchEvent(n)):void 0},v=function(){var t,e
return null!=(t=null!=(e=window.performance)&&"function"==typeof e.now?e.now():void 0)?t:+new Date},x=function(t,e){return null==e&&(e=0),e?(t*=Math.pow(10,e),t+=.5,t=Math.floor(t),t/=Math.pow(10,e)):Math.round(t)},I=function(t){return 0>t?Math.ceil(t):Math.floor(t)},b=function(t){return t-x(t)},S=!1,(A=function(){var t,e,n,i,s
if(!S&&null!=window.jQuery){for(S=!0,i=["html","text"],s=[],e=0,n=i.length;n>e;e++)t=i[e],s.push(function(t){var e
return e=window.jQuery.fn[t],window.jQuery.fn[t]=function(t){var n
return null==t||null==(null!=(n=this[0])?n.odometer:void 0)?e.apply(this,arguments):this[0].odometer.update(t)}}(t))
return s}})(),setTimeout(A,0),d=function(){function t(e){var n,i,s,a,r,u,c,d,p,m,f=this
if(this.options=e,this.el=this.options.el,null!=this.el.odometer)return this.el.odometer
this.el.odometer=this,d=t.options
for(i in d)a=d[i],null==this.options[i]&&(this.options[i]=a)
null==(r=this.options).duration&&(r.duration=o),this.MAX_VALUES=this.options.duration/l/h|0,this.resetFormat(),this.value=this.cleanValue(null!=(p=this.options.value)?p:""),this.renderInside(),this.render()
try{for(m=["innerHTML","innerText","textContent"],u=0,c=m.length;c>u;u++)s=m[u],null!=this.el[s]&&!function(t){return Object.defineProperty(f.el,t,{get:function(){var e
return"innerHTML"===t?f.inside.outerHTML:null!=(e=f.inside.innerText)?e:f.inside.textContent},set:function(t){return f.update(t)}})}(s)}catch(y){n=y,this.watchForMutations()}}return t.prototype.renderInside=function(){return this.inside=document.createElement("div"),this.inside.className="odometer-inside",this.el.innerHTML="",this.el.appendChild(this.inside)},t.prototype.watchForMutations=function(){var t,e=this
if(null!=c)try{return null==this.observer&&(this.observer=new c(function(){var t
return t=e.el.innerText,e.renderInside(),e.render(e.value),e.update(t)})),this.watchMutations=!0,this.startWatchingMutations()}catch(n){t=n}},t.prototype.startWatchingMutations=function(){return this.watchMutations?this.observer.observe(this.el,{childList:!0}):void 0},t.prototype.stopWatchingMutations=function(){var t
return null!=(t=this.observer)?t.disconnect():void 0},t.prototype.cleanValue=function(t){var e
return"string"==typeof t&&(t=t.replace(null!=(e=this.format.radix)?e:".","<radix>"),t=t.replace(/[.,]/g,""),t=t.replace("<radix>","."),t=parseFloat(t,10)||0),x(t,this.format.precision)},t.prototype.bindTransitionEnd=function(){var t,e,n,i,s,o,a=this
if(!this.transitionEndBound){for(this.transitionEndBound=!0,e=!1,s=m.split(" "),o=[],n=0,i=s.length;i>n;n++)t=s[n],o.push(this.el.addEventListener(t,function(){return e?!0:(e=!0,setTimeout(function(){return a.render(),e=!1,C(a.el,"odometerdone")},0),!0)},!1))
return o}},t.prototype.resetFormat=function(){var t,e,i,s,o,a,u,h
if(t=null!=(u=this.options.format)?u:n,t||(t="d"),i=r.exec(t),!i)throw Error("Odometer: Unparsable digit format")
return h=i.slice(1,4),a=h[0],o=h[1],e=h[2],s=(null!=e?e.length:void 0)||0,this.format={repeating:a,radix:o,precision:s}},t.prototype.render=function(t){var e,n,i,s,o,a,r,u,h,l,c,d
for(null==t&&(t=this.value),this.stopWatchingMutations(),this.resetFormat(),this.inside.innerHTML="",a=this.options.theme,e=this.el.className.split(" "),o=[],u=0,l=e.length;l>u;u++)n=e[u],n.length&&((s=/^odometer-theme-(.+)$/.exec(n))?a=s[1]:/^odometer(-|$)/.test(n)||o.push(n))
for(o.push("odometer"),f||o.push("odometer-no-transitions"),o.push(a?"odometer-theme-"+a:"odometer-auto-theme"),this.el.className=o.join(" "),this.ribbons={},this.digits=[],r=!this.format.precision||!b(t)||!1,d=(""+t).split("").reverse(),h=0,c=d.length;c>h;h++)i=d[h],"."===i&&(r=!0),this.addDigit(i,r)
return this.startWatchingMutations()},t.prototype.update=function(t){var e,n=this
return t=this.cleanValue(t),(e=t-this.value)?(T(this.el,"odometer-animating-up odometer-animating-down odometer-animating"),e>0?w(this.el,"odometer-animating-up"):w(this.el,"odometer-animating-down"),this.stopWatchingMutations(),this.animate(t),this.startWatchingMutations(),setTimeout(function(){return n.el.offsetHeight,w(n.el,"odometer-animating")},0),this.value=t):void 0},t.prototype.renderDigit=function(){return g(i)},t.prototype.insertDigit=function(t,e){return null!=e?this.inside.insertBefore(t,e):this.inside.children.length?this.inside.insertBefore(t,this.inside.children[0]):this.inside.appendChild(t)},t.prototype.addSpacer=function(t,e,n){var i
return i=g(a),i.innerHTML=t,n&&w(i,n),this.insertDigit(i,e)},t.prototype.addDigit=function(t,e){var n,i,s,o
if(null==e&&(e=!0),"-"===t)return this.addSpacer(t,null,"odometer-negation-mark")
if("."===t)return this.addSpacer(null!=(o=this.format.radix)?o:".",null,"odometer-radix-mark")
if(e)for(s=!1;;){if(!this.format.repeating.length){if(s)throw Error("Bad odometer format without digits")
this.resetFormat(),s=!0}if(n=this.format.repeating[this.format.repeating.length-1],this.format.repeating=this.format.repeating.substring(0,this.format.repeating.length-1),"d"===n)break
this.addSpacer(n)}return i=this.renderDigit(),i.querySelector(".odometer-value").innerHTML=t,this.digits.push(i),this.insertDigit(i)},t.prototype.animate=function(t){return f&&"count"!==this.options.animation?this.animateSlide(t):this.animateCount(t)},t.prototype.animateCount=function(t){var n,i,s,o,a,r=this
return(i=+t-this.value)?(o=s=v(),n=this.value,(a=function(){var u,h,l
return v()-o>r.options.duration?(r.value=t,r.render(),void C(r.el,"odometerdone")):(u=v()-s,u>e&&(s=v(),l=u/r.options.duration,h=i*l,n+=h,r.render(Math.round(n))),null!=M?M(a):setTimeout(a,e))})()):void 0},t.prototype.getDigitCount=function(){var t,e,n,i,s,o
for(i=1<=arguments.length?N.call(arguments,0):[],t=s=0,o=i.length;o>s;t=++s)n=i[t],i[t]=Math.abs(n)
return e=Math.max.apply(Math,i),Math.ceil(Math.log(e+1)/Math.log(10))},t.prototype.getFractionalDigitCount=function(){var t,e,n,i,s,o,a
for(s=1<=arguments.length?N.call(arguments,0):[],e=/^\-?\d*\.(\d*?)0*$/,t=o=0,a=s.length;a>o;t=++o)i=s[t],s[t]=""+i,n=e.exec(s[t]),s[t]=null==n?0:n[1].length
return Math.max.apply(Math,s)},t.prototype.resetDigits=function(){return this.digits=[],this.ribbons=[],this.inside.innerHTML="",this.resetFormat()},t.prototype.animateSlide=function(t){var e,n,i,o,a,r,u,h,l,c,d,p,m,f,y,g,b,v,T,M,x,k,C,A,S,L,_
if(g=this.value,h=this.getFractionalDigitCount(g,t),h&&(t*=Math.pow(10,h),g*=Math.pow(10,h)),i=t-g){for(this.bindTransitionEnd(),o=this.getDigitCount(g,t),a=[],e=0,d=T=0;o>=0?o>T:T>o;d=o>=0?++T:--T){if(b=I(g/Math.pow(10,o-d-1)),u=I(t/Math.pow(10,o-d-1)),r=u-b,Math.abs(r)>this.MAX_VALUES){for(c=[],p=r/(this.MAX_VALUES+this.MAX_VALUES*e*s),n=b;r>0&&u>n||0>r&&n>u;)c.push(Math.round(n)),n+=p
c[c.length-1]!==u&&c.push(u),e++}else c=function(){_=[]
for(var t=b;u>=b?u>=t:t>=u;u>=b?t++:t--)_.push(t)
return _}.apply(this)
for(d=M=0,k=c.length;k>M;d=++M)l=c[d],c[d]=Math.abs(l%10)
a.push(c)}for(this.resetDigits(),L=a.reverse(),d=x=0,C=L.length;C>x;d=++x)for(c=L[d],this.digits[d]||this.addDigit(" ",d>=h),null==(v=this.ribbons)[d]&&(v[d]=this.digits[d].querySelector(".odometer-ribbon-inner")),this.ribbons[d].innerHTML="",0>i&&(c=c.reverse()),m=S=0,A=c.length;A>S;m=++S)l=c[m],y=document.createElement("div"),y.className="odometer-value",y.innerHTML=l,this.ribbons[d].appendChild(y),m===c.length-1&&w(y,"odometer-last-value"),0===m&&w(y,"odometer-first-value")
return 0>b&&this.addDigit("-"),f=this.inside.querySelector(".odometer-radix-mark"),null!=f&&f.parent.removeChild(f),h?this.addSpacer(this.format.radix,this.digits[h-1],"odometer-radix-mark"):void 0}},t}(),d.options=null!=(_=window.odometerOptions)?_:{},setTimeout(function(){var t,e,n,i,s
if(window.odometerOptions){i=window.odometerOptions,s=[]
for(t in i)e=i[t],s.push(null!=(n=d.options)[t]?(n=d.options)[t]:n[t]=e)
return s}},0),d.init=function(){var t,e,n,i,s,o
if(null!=document.querySelectorAll){for(e=document.querySelectorAll(d.options.selector||".odometer"),o=[],n=0,i=e.length;i>n;n++)t=e[n],o.push(t.odometer=new d({el:t,value:null!=(s=t.innerText)?s:t.textContent}))
return o}},null!=(null!=(E=document.documentElement)?E.doScroll:void 0)&&null!=document.createEventObject?(L=document.onreadystatechange,document.onreadystatechange=function(){return"complete"===document.readyState&&d.options.auto!==!1&&d.init(),null!=L?L.apply(this,arguments):void 0}):document.addEventListener("DOMContentLoaded",function(){return d.options.auto!==!1?d.init():void 0},!1),"function"==typeof define&&define.amd?define(["jquery"],function(){return d}):typeof exports===!1?module.exports=d:window.Odometer=d}.call(this),FF(),window.onpopstate=function(t){FF()},home){_("happyMarquee").style.display="block"
for(var t=0;5>t;t++)setTimeout(function(){_("nameLink").style.border="3px solid #00FF00"},2e3+500*t),setTimeout(function(){_("nameLink").style.border="3px solid green"},2250+500*t)
setTimeout(function(){_("nameLink").style.borderStyle="none"},8e3),happyID=setTimeout(function(){O(happyMarquee,2e3),setTimeout(function(){_("happyMarquee").style.display="none"},2e3)},3e3)}showID=setTimeout(function(){showBtn&&(N(subscribeButton,2e3),JJ(channelThumbnail,2e3))},3e3)
var soundEnabled=!1,nightEnabled=!1
document.onkeypress=LL

